AVAILABLE_MODELS:
- BAAI/bge-large-en-v1.5
- BAAI/bge-base-en-v1.5
- BAAI/bge-small-en-v1.5
- BAAI/bge-large-en
- BAAI/bge-base-en
- BAAI/bge-small-en
- thenlper/gte-large
- thenlper/gte-base
- thenlper/gte-small
- intfloat/e5-large-v2
- intfloat/multilingual-e5-large
- intfloat/e5-base-v2
- intfloat/multilingual-e5-base
- intfloat/e5-small-v2
- intfloat/multilingual-e5-small
- hkunlp/instructor-xl
- hkunlp/instructor-large
- hkunlp/instructor-base
- sentence-transformers/all-mpnet-base-v2
- sentence-transformers/all-MiniLM-L12-v2
- sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
- sentence-transformers/all-MiniLM-L6-v2
- sentence-transformers/multi-qa-MiniLM-L6-cos-v1
- sentence-transformers/sentence-t5-xl
- sentence-transformers/sentence-t5-large
- sentence-transformers/sentence-t5-base
- sentence-transformers/gtr-t5-xl
- sentence-transformers/gtr-t5-large
- sentence-transformers/gtr-t5-base
COMPUTE_DEVICE: cuda
EMBEDDING_MODEL_NAME: C:/PATH/Scripts/ChromaDB-Plugin-for-LM-Studio/v2_2_2 - working/Embedding_Models/BAAI--bge-base-en-v1.5
server:
  api_key: ''
  connection_str: http://localhost:1234/v1
  model_max_tokens: 500
  model_temperature: 0.1
  prefix: '[INST]'
  suffix: '[/INST]'
styles:
  button: 'background-color: #323842; color: light gray; font: 10pt "Segoe UI Historic";
    width: 29;'
  frame: 'background-color: #161b22;'
  input: 'background-color: #2e333b; color: light gray; font: 13pt "Segoe UI Historic";'
  text: 'background-color: #092327; color: light gray; font: 12pt "Segoe UI Historic";'
