AVAILABLE_MODELS:
- BAAI/bge-large-en
- BAAI/bge-base-en
- BAAI/bge-small-en
- thenlper/gte-large
- thenlper/gte-base
- thenlper/gte-small
- intfloat/e5-large-v2
- intfloat/e5-base-v2
- intfloat/e5-small-v2
- hkunlp/instructor-xl
- hkunlp/instructor-large
- hkunlp/instructor-base
- sentence-transformers/all-mpnet-base-v2
- sentence-transformers/all-MiniLM-L12-v2
- sentence-transformers/all-MiniLM-L6-v2
COMPUTE_DEVICE: cuda
DOCUMENT_MAP:
  .csv: UnstructuredCSVLoader
  .docx: Docx2txtLoader
  .eml: UnstructuredEmailLoader
  .enex: EverNoteLoader
  .json: JSONLoader
  .msg: UnstructuredEmailLoader
  .pdf: PDFMinerLoader
  .txt: TextLoader
  .xls: UnstructuredExcelLoader
  .xlsx: UnstructuredExcelLoader
EMBEDDING_MODEL_NAME: C:/PATH/Scripts/LM Search Vector Database_v1_4_2/Embedding_Models/BAAI--bge-large-en
