AVAILABLE_MODELS:
- BAAI/bge-base-en-v1.5
- BAAI/bge-large-en-v1.5
- BAAI/bge-small-en-v1.5
- hkunlp/instructor-base
- hkunlp/instructor-large
- hkunlp/instructor-xl
- jinaai/jina-embedding-b-en-v1
- jinaai/jina-embedding-l-en-v1
- jinaai/jina-embedding-s-en-v1
- jinaai/jina-embedding-t-en-v1
- sentence-transformers/all-distilroberta-v1
- sentence-transformers/all-MiniLM-L6-v2
- sentence-transformers/all-mpnet-base-v2
- sentence-transformers/gtr-t5-base
- sentence-transformers/gtr-t5-large
- sentence-transformers/gtr-t5-xl
- sentence-transformers/msmarco-distilbert-base-v4
- sentence-transformers/msmarco-distilbert-cos-v5
- sentence-transformers/msmarco-MiniLM-L-6-v3
- sentence-transformers/msmarco-MiniLM-L6-cos-v5
- sentence-transformers/msmarco-roberta-base-v3
- sentence-transformers/multi-qa-distilbert-cos-v1
- sentence-transformers/multi-qa-MiniLM-L6-cos-v1
- sentence-transformers/multi-qa-mpnet-base-cos-v1
- sentence-transformers/sentence-t5-base
- sentence-transformers/sentence-t5-large
- sentence-transformers/sentence-t5-xl
- thenlper/gte-base
- thenlper/gte-large
- thenlper/gte-small
COMPUTE_DEVICE: cuda
Compute_Device:
  available:
  - cuda
  - cpu
  database_creation: cuda
  database_query: cpu
EMBEDDING_MODEL_NAME: C:/PATH/Scripts/ChromaDB-Plugin-for-LM-Studio/v2_6_2 - working/Embedding_Models/sentence-transformers--all-MiniLM-L6-v2
database:
  chunk_overlap: 250
  chunk_size: 700
  contexts: 10
  device: null
  similarity: 0.9
embedding-models:
  bge:
    query_instruction: 'Represent this sentence for searching relevant passages:'
  instructor:
    embed_instruction: 'Represent the document for retrieval:'
    query_instruction: 'Represent the question for retrieving supporting documents:'
server:
  api_key: ''
  connection_str: http://localhost:1234/v1
  model_max_tokens: -1
  model_temperature: 0.1
  prefix: '[INST]'
  suffix: '[/INST]'
styles:
  button: 'background-color: #323842; color: light gray; font: 10pt "Segoe UI Historic";
    width: 29;'
  frame: 'background-color: #161b22;'
  input: 'background-color: #2e333b; color: light gray; font: 13pt "Segoe UI Historic";'
  text: 'background-color: #092327; color: light gray; font: 12pt "Segoe UI Historic";'
transcribe_file:
  device: cuda
  file: C:/PATH/Scripts/ChromaDB-Plugin-for-LM-Studio/v2_6_1 - working/test.wma
  language: Option 1
  model: small.en
  quant: float16
  timestamps: true
  translate: false
transcriber:
  device: cuda
  model: small.en
  quant: float32
