Compute_Device:
  available:
  - cpu
  database_creation: cpu
  database_query: cpu
  gpu_brand: 
EMBEDDING_MODEL_NAME: 
Platform_Info:
  os: 
Supported_CTranslate2_Quantizations:
  CPU:
  GPU:
bark:
  enable_cpu_offload: false
  model_precision: float16
  size: normal
  speaker: v2/en_speaker_6
  use_better_transformer: true
created_databases: {}
database:
  chunk_overlap: 200
  chunk_size: 800
  contexts: '10'
  database_to_search: 
  document_types: ''
  search_term: ''
  similarity: 0.3
embedding-models:
  bge:
    query_instruction: 'Represent this sentence for searching relevant passages:'
  instructor:
    embed_instruction: 'Represent the document for retrieval:'
    query_instruction: 'Represent the question for retrieving supporting documents:'
server:
  api_key: ''
  connection_str: http://localhost:1234/v1
  model_max_tokens: -1
  model_temperature: 0.1
  prefix: '### User:'
  prefix_chat_ml: <|im_start|>
  prefix_llama2_and_mistral: '[INST]'
  prefix_neural_chat: '### User:'
  prefix_orca2: <|im_start|>user
  prefix_stablelm-zephyr: <|user|>
  prompt_format_disabled: false
  suffix: '### Assistant:'
  suffix_chat_ml: <|im_end|>
  suffix_llama2_and_mistral: '[/INST]'
  suffix_neural_chat: '### Assistant:'
  suffix_orca2: <|im_end|><|im_start|>assistant
  suffix_stablelm-zephyr: <|endoftext|> <|assistant|>
styles:
  button: 'background-color: #323842; color: light gray; font: 10pt "Segoe UI Historic";
    width: 29;'
  frame: 'background-color: #161b22;'
  input: 'background-color: #2e333b; color: light gray; font: 13pt "Segoe UI Historic";'
  text: 'background-color: #092327; color: light gray; font: 12pt "Segoe UI Historic";'
transcribe_file:
  device: cpu
  file: null
  model: whisper-large-v2
  quant: float16
  timestamps: true
transcriber:
  device: cpu
  model: whisper-small.en
  quant: float32
vision:
  bakllava:
    available_quants:
    - 4-bit
    - 8-bit
    - float16
    available_sizes:
    - 7b
  batch: null
  chosen_model: bakllava
  chosen_quant: float16
  chosen_size: 7b
  cogvlm:
    available_quants:
    - 4-bit
    - 8-bit
    available_sizes:
    - 17.6b
  flash_attention2: null
  llava:
    available_quants:
    - 4-bit
    - 8-bit
    - float16
    available_sizes:
    - 7b
    - 13b
  salesforce:
    available_quants:
    - float32
    available_sizes:
    - 470m
  test_image: 
