AVAILABLE_MODELS:
- details:
    description: Well rounded & customizable.
    dimensions: 384
    max_sequence: 512
    size_mb: 134
  model: BAAI/bge-small-en-v1.5
- details:
    description: Well rounded & customizable.
    dimensions: 768
    max_sequence: 512
    size_mb: 438
  model: BAAI/bge-base-en-v1.5
- details:
    description: Well rounded & slight RAG improvement.
    dimensions: 768
    max_sequence: 512
    size_mb: 438
  model: BAAI/llm-embedder
- details:
    description: Well rounded & customizable.
    dimensions: 1024
    max_sequence: 512
    size_mb: 1340
  model: BAAI/bge-large-en-v1.5
- details:
    description: Well rounded & customizable.
    dimensions: 768
    max_sequence: 512
    size_mb: 439
  model: hkunlp/instructor-base
- details:
    description: Well rounded & customizable.
    dimensions: 1024
    max_sequence: 512
    size_mb: 1340
  model: hkunlp/instructor-large
- details:
    description: Well rounded & customizable.
    dimensions: 1024
    max_sequence: 512
    size_mb: 4960
  model: hkunlp/instructor-xl
- details:
    description: Well rounded
    dimensions: 312
    max_sequence: 512
    size_mb: 58
  model: jinaai/jina-embedding-t-en-v1
- details:
    description: Well rounded
    dimensions: 512
    max_sequence: 512
    size_mb: 141
  model: jinaai/jina-embedding-s-en-v1
- details:
    description: Well rounded
    dimensions: 768
    max_sequence: 512
    size_mb: 439
  model: jinaai/jina-embedding-b-en-v1
- details:
    description: Well rounded
    dimensions: 1024
    max_sequence: 512
    size_mb: 1340
  model: jinaai/jina-embedding-l-en-v1
- details:
    description: Clustering or semantic search
    dimensions: 768
    max_sequence: 512
    size_mb: 329
  model: sentence-transformers/all-distilroberta-v1
- details:
    description: Clustering or semantic search
    dimensions: 384
    max_sequence: 256
    size_mb: 91
  model: sentence-transformers/all-MiniLM-L6-v2
- details:
    description: Clustering or semantic search
    dimensions: 768
    max_sequence: 384
    size_mb: 438
  model: sentence-transformers/all-mpnet-base-v2
- details:
    description: Semantic search.
    dimensions: 768
    max_sequence: 512
    size_mb: 219
  model: sentence-transformers/gtr-t5-base
- details:
    description: Semantic search.
    dimensions: 768
    max_sequence: 512
    size_mb: 670
  model: sentence-transformers/gtr-t5-large
- details:
    description: Semantic search.
    dimensions: 768
    max_sequence: 512
    size_mb: 2480
  model: sentence-transformers/gtr-t5-xl
- details:
    description: Clustering or semantic search
    dimensions: 768
    max_sequence: 512
    size_mb: 265
  model: sentence-transformers/msmarco-distilbert-base-v4
- details:
    description: Semantic search.
    dimensions: 768
    max_sequence: 384
    size_mb: 265
  model: sentence-transformers/msmarco-distilbert-cos-v5
- details:
    description: Clustering or semantic search
    dimensions: 384
    max_sequence: 512
    size_mb: 91
  model: sentence-transformers/msmarco-MiniLM-L-6-v3
- details:
    description: Semantic search.
    dimensions: 384
    max_sequence: 384
    size_mb: 91
  model: sentence-transformers/msmarco-MiniLM-L6-cos-v5
- details:
    description: Clustering or semantic search
    dimensions: 768
    max_sequence: 510
    size_mb: 499
  model: sentence-transformers/msmarco-roberta-base-v3
- details:
    description: Semantic search.
    dimensions: 768
    max_sequence: 512
    size_mb: 265
  model: sentence-transformers/multi-qa-distilbert-cos-v1
- details:
    description: Semantic search.
    dimensions: 384
    max_sequence: 512
    size_mb: 91
  model: sentence-transformers/multi-qa-MiniLM-L6-cos-v1
- details:
    description: Semantic search.
    dimensions: 768
    max_sequence: 512
    size_mb: 438
  model: sentence-transformers/multi-qa-mpnet-base-cos-v1
- details:
    description: Sentence similarity
    dimensions: 768
    max_sequence: 256
    size_mb: 219
  model: sentence-transformers/sentence-t5-base
- details:
    description: Sentence similarity
    dimensions: 768
    max_sequence: 256
    size_mb: 670
  model: sentence-transformers/sentence-t5-large
- details:
    description: Sentence similarity
    dimensions: 768
    max_sequence: 256
    size_mb: 2480
  model: sentence-transformers/sentence-t5-xl
- details:
    description: Well rounded
    dimensions: 384
    max_sequence: 512
    size_mb: 67
  model: thenlper/gte-small
- details:
    description: Well rounded
    dimensions: 768
    max_sequence: 512
    size_mb: 219
  model: thenlper/gte-base
- details:
    description: Well rounded
    dimensions: 1024
    max_sequence: 512
    size_mb: 670
  model: thenlper/gte-large
COMPUTE_DEVICE: cuda
Compute_Device:
  available:
  - cuda
  - cpu
  database_creation: cuda
  database_query: cpu
EMBEDDING_MODEL_NAME: C:/PATH/Scripts/ChromaDB-Plugin-for-LM-Studio/v2_6_2 - working/Embedding_Models/BAAI--llm-embedder
database:
  chunk_overlap: 250
  chunk_size: 700
  contexts: 10
  device: null
  similarity: 0.9
embedding-models:
  bge:
    query_instruction: 'Represent this sentence for searching relevant passages:'
  instructor:
    embed_instruction: 'Represent the document for retrieval:'
    query_instruction: 'Represent the question for retrieving supporting documents:'
server:
  api_key: ''
  connection_str: http://localhost:1234/v1
  model_max_tokens: -1
  model_temperature: 0.1
  prefix: '[INST]'
  suffix: '[/INST]'
styles:
  button: 'background-color: #323842; color: light gray; font: 10pt "Segoe UI Historic";
    width: 29;'
  frame: 'background-color: #161b22;'
  input: 'background-color: #2e333b; color: light gray; font: 13pt "Segoe UI Historic";'
  text: 'background-color: #092327; color: light gray; font: 12pt "Segoe UI Historic";'
transcribe_file:
  device: cuda
  file: C:/PATH/Scripts/ChromaDB-Plugin-for-LM-Studio/v2_6_1 - working/test.wma
  language: Option 1
  model: small.en
  quant: float16
  timestamps: true
  translate: false
transcriber:
  device: cuda
  model: small.en
  quant: float32
